version: "3.8"

services:
  ojito:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"

  api:
    image: r8.im/greatnoobkiller/resnet@sha256:0b4f476526f2e9b88fbede22406b0c851736f70dafc2091c5e1d1628008b49c4
    ports:
      - "80:5000"
